// Code generated by "stringer -type=ItemType"; DO NOT EDIT.

package items

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DotfileItem-0]
	_ = x[RoguItem-1]
	_ = x[FileItem-2]
	_ = x[ScriptItem-3]
}

const _ItemType_name = "DotfileItemRoguItemFileItemScriptItem"

var _ItemType_index = [...]uint8{0, 11, 19, 27, 37}

func (i ItemType) String() string {
	if i < 0 || i >= ItemType(len(_ItemType_index)-1) {
		return "ItemType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ItemType_name[_ItemType_index[i]:_ItemType_index[i+1]]
}
